/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2018-06-26 02:46:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewtest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"../../otherlib/easyui/jquery.min.js\"></script> -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"E:\\spaceall\\spacegit\\git\\yhzh\\project\\cmstest\\WebContent\\otherlib\\easyui\\jquery.min.js\"></script> -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://localhost:8080/HXPTADAPTER/otherlib/easyui/jquery.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction ajaxTest(){\r\n");
      out.write("\t\t//alert(11);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t   url:\"http://localhost:8080/cmstest/helloAjax1\",\r\n");
      out.write("\t\t\t   //url:\"/helloAjax1\",\r\n");
      out.write("\t\t\t   type:\"post\",\r\n");
      out.write("\t\t\t   //dataType:\"text\", //这样返回的就是一个json字符串\r\n");
      out.write("\t\t\t   dataType:\"json\", //这样返回的就是一个json对象\r\n");
      out.write("\t\t\t   data:{\r\n");
      out.write("\t\t\t\t   mypara1:\"zhangsan\",\r\n");
      out.write("\t\t\t\t   mypara2:\"哈哈入参2mypara2\"\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   success:function(responseText){\r\n");
      out.write("\t\t\t     alert(responseText);\r\n");
      out.write("\t\t\t     alert(responseText.age);\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   error:function(){\r\n");
      out.write("\t\t\t     alert(\"system error\");\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction ajaxTest2(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t   url:\"http://localhost:8080/cmstest/helloAjax2\",\r\n");
      out.write("\t\t\t   type:\"post\",\r\n");
      out.write("\t\t\t   //dataType:\"text\", //这样返回的就是一个json字符串\r\n");
      out.write("\t\t\t   dataType:\"json\", //这样返回的就是一个json对象\r\n");
      out.write("\t\t\t   data:{\r\n");
      out.write("\t\t\t\t   homenameIn:\"zhangsan22\",\r\n");
      out.write("\t\t\t\t   mypara2:\"哈哈入参2mypara2\"\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   success:function(responseText){\r\n");
      out.write("\t\t\t     alert(responseText);\r\n");
      out.write("\t\t\t     alert(responseText.age);\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   error:function(){\r\n");
      out.write("\t\t\t     alert(\"system error\");\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction ajaxTest3(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t   url:\"http://localhost:8080/cmstest/helloAjax3\",\r\n");
      out.write("\t\t\t   type:\"post\",\r\n");
      out.write("\t\t\t   //dataType:\"text\", //这样返回的就是一个json字符串\r\n");
      out.write("\t\t\t   dataType:\"json\", //这样返回的就是一个json对象\r\n");
      out.write("\t\t\t   data:{\r\n");
      out.write("\t\t\t\t   homenameIn:\"zhangsan33\",\r\n");
      out.write("\t\t\t\t   mypara2:\"哈哈入参23mypara3\"\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   success:function(responseText){\r\n");
      out.write("\t\t\t     alert(responseText);\r\n");
      out.write("\t\t\t     alert(responseText.age);\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   error:function(){\r\n");
      out.write("\t\t\t     alert(\"system error\");\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction ajaxTest3_2(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t   url:\"http://localhost:8080/cmstest/helloAjax3_2\",\r\n");
      out.write("\t\t\t   type:\"post\",\r\n");
      out.write("\t\t\t   //dataType:\"text\", //这样返回的就是一个json字符串\r\n");
      out.write("\t\t\t   dataType:\"json\", //这样返回的就是一个json对象\r\n");
      out.write("\t\t\t   data:{\r\n");
      out.write("\t\t\t\t   name:\"zhangsan33\",\r\n");
      out.write("\t\t\t\t   text:\"哈哈入参23mypara3\"\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   success:function(responseText){\r\n");
      out.write("\t\t\t     alert(responseText);\r\n");
      out.write("\t\t\t     alert(responseText.age);\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   error:function(){\r\n");
      out.write("\t\t\t     alert(\"system error\");\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction ajaxTest4(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t   url:\"http://localhost:8080/cmstest/helloAjax4\",\r\n");
      out.write("\t\t\t   type:\"post\",\r\n");
      out.write("\t\t\t   //dataType:\"text\", //这样返回的就是一个json字符串\r\n");
      out.write("\t\t\t   dataType:\"json\", //这样返回的就是一个json对象\r\n");
      out.write("\t\t\t   data:{\r\n");
      out.write("\t\t\t\t   username:\"zhangsan44\",\r\n");
      out.write("\t\t\t\t   mypara2:\"哈哈入参23mypara3\"\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   success:function(responseText){\r\n");
      out.write("\t\t\t     alert(responseText);\r\n");
      out.write("\t\t\t     alert(responseText[0].out1);\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   error:function(){\r\n");
      out.write("\t\t\t     alert(\"system error\");\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction ajaxTest5(){\r\n");
      out.write("\t\tvar map = [];\r\n");
      out.write("\t\tmap.username = \"zhangsan55\";\r\n");
      out.write("\t\tmap.mypara2 = \"哈哈入参mypara55\";\r\n");
      out.write("\t\tvar para = \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t\t username:\"zhangsan44\",\r\n");
      out.write("\t\t\t\t mypara2:\"哈哈入参23mypara3\"\t\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t/* {\r\n");
      out.write("\t\t\tmap: map\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t   url:\"http://localhost:8080/cmstest/helloAjax5\",\r\n");
      out.write("\t\t\t   type:\"post\",\r\n");
      out.write("\t\t\t   //dataType:\"text\", //这样返回的就是一个json字符串\r\n");
      out.write("\t\t\t   dataType:\"json\", //这样返回的就是一个json对象\r\n");
      out.write("\t\t\t   contentType:'application/json;charset=UTF-8',//关键是要加上这行\r\n");
      out.write("\t\t       traditional:true,//这使json格式的字符不会被转码\r\n");
      out.write("\t\t       data:JSON.stringify(para),\r\n");
      out.write("\t\t\t   success:function(responseText){\r\n");
      out.write("\t\t\t     alert(responseText);\r\n");
      out.write("\t\t\t     alert(responseText[0].out1);\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   error:function(){\r\n");
      out.write("\t\t\t     alert(\"system error\");\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction ajaxTest5_2(){\r\n");
      out.write("\t\tvar list =[\r\n");
      out.write("\t\t\t{username:\"zhangsan51\",mypara2:\"哈哈入参mypara51\"},\r\n");
      out.write("\t\t\t{username:\"zhangsan52\",mypara2:\"哈哈入参mypara52\"},\r\n");
      out.write("\t\t\t{username:\"zhangsan53\",mypara2:\"哈哈入参mypara53\"},\r\n");
      out.write("\t\t\t{username:\"zhangsan54\",mypara2:\"哈哈入参mypara56\"},\r\n");
      out.write("\t\t\t{username:\"zhangsan58\",mypara2:\"哈哈入参mypara58\"}\r\n");
      out.write("\t\t];\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t   url:\"http://localhost:8080/cmstest/helloAjax5_2\",\r\n");
      out.write("\t\t\t   type:\"post\",\r\n");
      out.write("\t\t\t   dataType:\"json\", //这样返回的就是一个json对象\r\n");
      out.write("\t\t\t   contentType:'application/json;charset=UTF-8',//关键是要加上这行\r\n");
      out.write("\t\t       traditional:true,//这使json格式的字符不会被转码\r\n");
      out.write("\t\t       data:JSON.stringify(list),\r\n");
      out.write("\t\t\t   success:function(responseText){\r\n");
      out.write("\t\t\t     alert(responseText);\r\n");
      out.write("\t\t\t     alert(responseText[0].out1);\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   error:function(){\r\n");
      out.write("\t\t\t     alert(\"system error\");\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/**\r\n");
      out.write("\tRestController测试1，非常成功\r\n");
      out.write("\t*/\r\n");
      out.write("\tfunction ajaxTest6(){\r\n");
      out.write("\t\tvar list =[\r\n");
      out.write("\t\t\t{username:\"zhangsan61\",mypara2:\"哈哈入参mypara61\"},\r\n");
      out.write("\t\t\t{username:\"zhangsan62\",mypara2:\"哈哈入参mypara62\"},\r\n");
      out.write("\t\t\t{username:\"zhangsan63\",mypara2:\"哈哈入参mypara63\"},\r\n");
      out.write("\t\t\t{username:\"zhangsan64\",mypara2:\"哈哈入参mypara66\"},\r\n");
      out.write("\t\t\t{username:\"zhangsan68\",mypara2:\"哈哈入参mypara68\"}\r\n");
      out.write("\t\t];\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t   url:\"http://localhost:8080/HXPTADAPTER/helloAjax6\",\r\n");
      out.write("\t\t\t   type:\"post\",\r\n");
      out.write("\t\t\t   dataType:\"json\", //这样返回的就是一个json对象\r\n");
      out.write("\t\t\t   contentType:'application/json;charset=UTF-8',//关键是要加上这行\r\n");
      out.write("\t\t       traditional:true,//这使json格式的字符不会被转码\r\n");
      out.write("\t\t       data:JSON.stringify(list),\r\n");
      out.write("\t\t\t   success:function(responseText){\r\n");
      out.write("\t\t\t     alert(responseText);\r\n");
      out.write("\t\t\t     alert(responseText[0].out1);\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   error:function(){\r\n");
      out.write("\t\t\t     alert(\"system error\");\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/**\r\n");
      out.write("\tRestController测试2,失败\r\n");
      out.write("\t*/\r\n");
      out.write("\tfunction ajaxTest6_2(){\r\n");
      out.write("\t\tvar list =[\r\n");
      out.write("\t\t\t{username:\"zhangsan61\",mypara2:\"哈哈入参mypara61\"},\r\n");
      out.write("\t\t\t{username:\"zhangsan62\",mypara2:\"哈哈入参mypara62\"},\r\n");
      out.write("\t\t\t{username:\"zhangsan63\",mypara2:\"哈哈入参mypara63\"},\r\n");
      out.write("\t\t\t{username:\"zhangsan64\",mypara2:\"哈哈入参mypara66\"},\r\n");
      out.write("\t\t\t{username:\"zhangsan68\",mypara2:\"哈哈入参mypara68\"}\r\n");
      out.write("\t\t];\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t   url:\"http://localhost:8080/HXPTADAPTER/helloAjax6_2\",\r\n");
      out.write("\t\t\t   type:\"post\",\r\n");
      out.write("\t\t\t   dataType:\"json\", //这样返回的就是一个json对象\r\n");
      out.write("\t\t\t   //contentType:'application/json;charset=UTF-8',//关键是要加上这行\r\n");
      out.write("\t\t       //traditional:true,//这使json格式的字符不会被转码\r\n");
      out.write("\t\t       data:list,\r\n");
      out.write("\t\t\t   success:function(responseText){\r\n");
      out.write("\t\t\t     alert(responseText);\r\n");
      out.write("\t\t\t     alert(responseText[0].out1);\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   error:function(){\r\n");
      out.write("\t\t\t     alert(\"system error\");\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/**\r\n");
      out.write("\tRestController测试3\r\n");
      out.write("\t*/\r\n");
      out.write("\tfunction ajaxTest6_3(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t   url:\"http://localhost:8080/HXPTADAPTER/helloAjax6_3\",\r\n");
      out.write("\t\t\t   type:\"post\",\r\n");
      out.write("\t\t\t   //dataType:\"text\", //这样返回的就是一个json字符串\r\n");
      out.write("\t\t\t   dataType:\"json\", //这样返回的就是一个json对象\r\n");
      out.write("\t\t\t   data:{\r\n");
      out.write("\t\t\t\t   username:\"RestController33\",\r\n");
      out.write("\t\t\t\t   mypara2:\"哈哈入参RestController3\"\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   success:function(responseText){\r\n");
      out.write("\t\t\t     alert(responseText);\r\n");
      out.write("\t\t\t     alert(responseText[0].out1);\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   error:function(){\r\n");
      out.write("\t\t\t     alert(\"system error\");\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//--------------以下是数据库操作测试---------------------------------------------------\r\n");
      out.write("\tfunction hellodao1(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t   url:\"http://localhost:8080/cmstest/hellodao1\",\r\n");
      out.write("\t\t\t   type:\"post\",\r\n");
      out.write("\t\t\t   //dataType:\"text\", //这样返回的就是一个json字符串\r\n");
      out.write("\t\t\t   dataType:\"json\", //这样返回的就是一个json对象\r\n");
      out.write("\t\t\t   data:{\r\n");
      out.write("\t\t\t\t   username:\"到dao1\",\r\n");
      out.write("\t\t\t\t   mypara2:\"哈哈入参23mypara3\"\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   success:function(responseText){\r\n");
      out.write("\t\t\t     alert(responseText);\r\n");
      out.write("\t\t\t     alert(responseText[0].out1);\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   error:function(){\r\n");
      out.write("\t\t\t     alert(\"system error\");\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t//随便为了触发后台测试\r\n");
      out.write("\tfunction hellodao1(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t   url:\"http://localhost:8080/cmstest/helloProper\",\r\n");
      out.write("\t\t\t   type:\"post\",\r\n");
      out.write("\t\t\t   //dataType:\"text\", //这样返回的就是一个json字符串\r\n");
      out.write("\t\t\t   dataType:\"json\", //这样返回的就是一个json对象\r\n");
      out.write("\t\t\t   data:{\r\n");
      out.write("\t\t\t\t   username:\"到dao1\",\r\n");
      out.write("\t\t\t\t   mypara2:\"哈哈入参23mypara3\"\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   success:function(responseText){\r\n");
      out.write("\t\t\t     alert(responseText);\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\t   error:function(){\r\n");
      out.write("\t\t\t     alert(\"system error\");\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\tjust test 随便测试个东西\tviewtest11\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<p>hello!!，我的出参2： ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${homeMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<input type=\"button\" id=\"mybutton\" value=\"按我ajax\" onclick=\"ajaxTest6_3()\"></input>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
